# Generated by Django 4.2.5 on 2025-10-02 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('certificationFile', models.FileField(upload_to='certifications/', verbose_name='认证文件')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('submissionDate', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('processedDate', models.DateTimeField(blank=True, null=True, verbose_name='处理日期')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_request', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
        ),
    ]
