# Generated by Django 4.2.5 on 2025-10-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chapter_collection_course_tag_subscription_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapterCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='completed_chapters',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', through='api.UserChapterCompletion', to='api.chapter'),
        ),
    ]
