# Generated by Django 4.2.5 on 2025-10-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userchaptercompletion_user_completed_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='options',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer',
            field=models.JSONField(blank=True, help_text='【仅供填空题使用】请在此处输入答案数组, 例如: ["答案A", "答案B"]', null=True, verbose_name='填空题答案'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('multiple-choice', '多选题'), ('fill-in-the-blank', '填空题')], max_length=20, verbose_name='题目类型'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否为正确答案')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.exercise')),
            ],
        ),
    ]
