# Generated by Django 4.2.5 on 2025-10-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_exercise_options_alter_exercise_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='答案解析'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='图片链接'),
        ),
    ]
