# Generated by Django 4.2.5 on 2025-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_exercise_explanation_exercise_image_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
