# Generated by Django 4.2.5 on 2025-10-07 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_community_communitypost_communityreply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='member',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='community',
            name='assistant',
        ),
        migrations.AddField(
            model_name='community',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assisted_communities', to=settings.AUTH_USER_MODEL, verbose_name='创始人助手'),
        ),
    ]
