# Generated by Django 4.2.5 on 2025-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_member_community_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationrequest',
            options={'verbose_name': '认证审批', 'verbose_name_plural': '认证审批'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': '练习', 'verbose_name_plural': '练习'},
        ),
        migrations.AlterModelOptions(
            name='gallerycollection',
            options={'verbose_name': '收藏画廊作品', 'verbose_name_plural': '收藏画廊作品'},
        ),
        migrations.AlterModelOptions(
            name='gallerydownloadrecord',
            options={'verbose_name': '画廊作品下载记录', 'verbose_name_plural': '画廊作品下载记录'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name': '画廊作品', 'verbose_name_plural': '画廊作品'},
        ),
        migrations.AlterModelOptions(
            name='galleryitemrating',
            options={'verbose_name': '画廊作品评分记录', 'verbose_name_plural': '画廊作品评分记录'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': '选项', 'verbose_name_plural': '选项'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '订阅', 'verbose_name_plural': '订阅'},
        ),
        migrations.AlterModelOptions(
            name='userchaptercompletion',
            options={'verbose_name': '完成章节', 'verbose_name_plural': '完成章节'},
        ),
        migrations.AddField(
            model_name='community',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='community_covers/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
    ]
