# Generated by Django 4.2.5 on 2025-10-07 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_certificationrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='related_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_access', to='api.course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='community',
            name='related_gallery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_access', to='api.galleryitem', verbose_name='关联画廊作品'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='communityreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
