# Generated by Django 4.2.5 on 2025-10-08 16:46

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_community_related_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=django_bleach.models.BleachField(verbose_name='帖子内容'),
        ),
        migrations.AlterField(
            model_name='communityreply',
            name='content',
            field=django_bleach.models.BleachField(verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_bleach.models.BleachField(verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='explanation',
            field=django_bleach.models.BleachField(blank=True, null=True, verbose_name='答案解析'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='prompt',
            field=django_bleach.models.BleachField(verbose_name='题干'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=django_bleach.models.BleachField(verbose_name='作品描述'),
        ),
    ]
