# Generated by Django 4.2.5 on 2025-10-09 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0015_alter_communitypost_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动数额')),
                ('description', models.CharField(max_length=255, verbose_name='变动原因')),
                ('transaction_type', models.CharField(choices=[('community_reward', '悬赏帖子'), ('purchase', '课程订阅'), ('download', '作品下载'), ('activity_reward', '活动积分'), ('admin_adjust', '管理员调整'), ('initial', '初始积分'), ('refund', '积分退回')], max_length=20, verbose_name='交易类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联内容ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='关联内容类型')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
            },
        ),
    ]
