# Generated by Django 4.2.5 on 2025-10-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pointstransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountStatus',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('frozen', 'frozen')], default='active', max_length=20),
        ),
    ]
