# Generated by Django 4.2.5 on 2025-10-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_accountstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('duration_days', models.PositiveIntegerField(verbose_name='有效天数')),
                ('price_points', models.PositiveIntegerField(verbose_name='所需积分')),
            ],
            options={
                'verbose_name': 'VIP套餐',
                'verbose_name_plural': 'VIP套餐',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='is_vip_free',
            field=models.BooleanField(default=False, verbose_name='VIP免费'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_vip_free',
            field=models.BooleanField(default=False, verbose_name='VIP免费'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP到期时间'),
        ),
    ]
