# Generated by Django 4.2.5 on 2025-10-09 09:47

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tag_created_at_tag_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=django_bleach.models.BleachField(blank=True, null=True, verbose_name='社群描述'),
        ),
    ]
