# Generated by Django 4.2.5 on 2025-10-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_community_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCertificationRequest',
            fields=[
            ],
            options={
                'verbose_name': '待处理认证',
                'verbose_name_plural': '待处理认证',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.certificationrequest',),
        ),
        migrations.CreateModel(
            name='PendingCommunityPost',
            fields=[
            ],
            options={
                'verbose_name': '待审核帖子',
                'verbose_name_plural': '待审核帖子',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.communitypost',),
        ),
        migrations.CreateModel(
            name='PendingCourse',
            fields=[
            ],
            options={
                'verbose_name': '待审核课程',
                'verbose_name_plural': '待审核课程',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.course',),
        ),
        migrations.CreateModel(
            name='PendingGalleryItem',
            fields=[
            ],
            options={
                'verbose_name': '待审核作品',
                'verbose_name_plural': '待审核作品',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.galleryitem',),
        ),
    ]
