# Generated by Django 4.2.5 on 2025-10-10 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0022_messagethread_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at'], 'verbose_name': '单条消息', 'verbose_name_plural': '单条消息'},
        ),
        migrations.AlterModelOptions(
            name='messagethread',
            options={'ordering': ['-created_at'], 'verbose_name': '站内信会话', 'verbose_name_plural': '站内信会话'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('notification', '系统通知'), ('conversation', '用户会话')], default='conversation', max_length=20, verbose_name='会话类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_bleach.models.BleachField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL, verbose_name='所有参与者'),
        ),
    ]
