# Generated by Django 4.2.5 on 2025-10-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_message_options_alter_messagethread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_covers/', verbose_name='封面图片'),
        ),
    ]
