# Generated by Django 4.2.5 on 2025-10-13 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_course_coverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='fill_in_blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.PositiveIntegerField(default=1, help_text='如果题目有多个填空位，标识这是第几个空', verbose_name='填空题答案序号')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='正确答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否为正确答案')),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='答案是否区分大小写')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题答案',
                'ordering': ['exercise', 'index_number'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.JSONField(verbose_name='用户提交的答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '用户提交',
                'verbose_name_plural': '用户提交',
            },
        ),
        migrations.AlterModelOptions(
            name='messagethread',
            options={'ordering': ['-created_at', '-last_message_at'], 'verbose_name': '站内信会话', 'verbose_name_plural': '站内信会话'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='answer',
        ),
        migrations.AddField(
            model_name='community',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='帖子总数'),
        ),
        migrations.AddField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('published', '已发布'), ('rejected', '已驳回'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='社群状态'),
        ),
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='downloaders',
            field=models.ManyToManyField(blank=True, related_name='downloaded_gallery_items', through='api.GalleryDownloadRecord', to=settings.AUTH_USER_MODEL, verbose_name='下载者'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='estimated_download_time',
            field=models.FloatField(default=0.0, verbose_name='估计下载时间(分钟)'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_cc_deleted',
            field=models.BooleanField(default=False, verbose_name='抄送人是否已删除'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_cc_read',
            field=models.BooleanField(default=False, verbose_name='抄送人是否已读'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_recipient_deleted',
            field=models.BooleanField(default=False, verbose_name='收件人是否已删除'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_recipient_read',
            field=models.BooleanField(default=False, verbose_name='收件人是否已读'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_sender_deleted',
            field=models.BooleanField(default=False, verbose_name='发信人是否已删除'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='最后一条消息时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=django_bleach.models.BleachField(blank=True, default='这是个神秘的人', max_length=120, null=True, verbose_name='用户介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='course_authored_count',
            field=models.PositiveIntegerField(default=0, verbose_name='创作的课程总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='软删除时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_beta_tester',
            field=models.BooleanField(default=False, verbose_name='是否为测试用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已软删除'),
        ),
        migrations.AddField(
            model_name='user',
            name='items_authored_count',
            field=models.PositiveIntegerField(default=0, verbose_name='创作的作品总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活动时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_authored_count',
            field=models.PositiveIntegerField(default=0, verbose_name='创作的帖子总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='unread_message_count',
            field=models.PositiveIntegerField(default=0, help_text='用于快速展示未读消息提示的缓存计数。', verbose_name='未读站内信总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信OpenID'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='status',
            field=models.CharField(choices=[('pending_review', '待审核'), ('published', '已发布'), ('closed', '已关闭'), ('rejected', '已驳回')], default='pending_review', max_length=20, verbose_name='帖子状态'),
        ),
        migrations.AlterField(
            model_name='course',
            name='collectors',
            field=models.ManyToManyField(blank=True, related_name='collected_courses', through='api.Collection', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('published', '已发布'), ('rejected', '已驳回'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_courses', through='api.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='订阅者'),
        ),
        migrations.AlterField(
            model_name='gallerycollection',
            name='gallery_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.galleryitem', verbose_name='收藏作品'),
        ),
        migrations.AlterField(
            model_name='gallerycollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AlterField(
            model_name='gallerydownloadrecord',
            name='downloaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='gallerydownloadrecord',
            name='gallery_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.galleryitem', verbose_name='下载作品'),
        ),
        migrations.AlterField(
            model_name='gallerydownloadrecord',
            name='points_spent',
            field=models.PositiveIntegerField(verbose_name='消耗积分'),
        ),
        migrations.AlterField(
            model_name='gallerydownloadrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下载用户'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='collectors',
            field=models.ManyToManyField(blank=True, related_name='collected_gallery_items', through='api.GalleryCollection', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.AlterField(
            model_name='galleryitemrating',
            name='gallery_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.galleryitem', verbose_name='评分对象'),
        ),
        migrations.AlterField(
            model_name='galleryitemrating',
            name='rated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评分时间'),
        ),
        migrations.AlterField(
            model_name='galleryitemrating',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='galleryitemrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评分用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accountStatus',
            field=models.CharField(choices=[('active', '活跃'), ('suspended', '已暂停'), ('frozen', '已冻结')], default='active', max_length=20, verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ageGroup',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='年龄组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currentPoints',
            field=models.PositiveIntegerField(default=0, verbose_name='当前总积分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='兴趣爱好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pointsStatus',
            field=models.CharField(choices=[('active', '活跃'), ('frozen', '已冻结')], default='active', max_length=20, verbose_name='积分状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('artist', '创作者'), ('admin', '管理员')], default='student', max_length=20, verbose_name='用户角色'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'accountStatus'], name='api_user_role_9728cd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['currentPoints'], name='api_user_current_9c7b06_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='api_user_is_dele_f19f7a_idx'),
        ),
        migrations.AddField(
            model_name='userexercisesubmission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.exercise', verbose_name='练习题'),
        ),
        migrations.AddField(
            model_name='userexercisesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='fill_in_blank',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blanks', to='api.exercise'),
        ),
    ]
