# Generated by Django 4.2.5 on 2025-10-14 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fill_in_blank_userexercisesubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用戶練習完成記錄',
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
