# Generated by Django 4.2.5 on 2025-10-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userexercisecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerydownloadrecord',
            name='version_at_download',
            field=models.CharField(blank=True, max_length=20, verbose_name='下载时版本'),
        ),
    ]
