# Generated by Django 4.2.5 on 2025-10-23 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_gallerydownloadrecord_version_at_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, help_text='执行此交易后用户的总余额 (currentPoints)', null=True, verbose_name='交易后余额'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.IntegerField(help_text='正数为收入, 负数为支出', verbose_name='变动数额'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('COURSE_PURCHASE', '课程订阅'), ('GALLERY_DOWNLOAD', '作品下载'), ('BOUNTY_POST', '发布悬赏'), ('COURSE_SALE', '售出课程'), ('GALLERY_SALE', '售出作品'), ('BOUNTY_AWARD', '赢得悬赏'), ('ACTIVITY_REWARD', '活动积分'), ('ADMIN_ADJUST', '管理员调整'), ('INITIAL', '初始积分'), ('REFUND', '积分退回')], db_index=True, max_length=50, verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', '-created_at'], name='api_pointst_user_id_385bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='api_pointst_content_1d81af_idx'),
        ),
    ]
