# backend/api/urls.py
from django.urls import path
from .views import (UserRegisterView,UserLoginView,UserProfileView,AvatarUpdateView,
PasswordResetRequestView,PasswordResetConfirmView,
ChangePhoneInitiateView, ChangePhoneVerifyNewView, ChangePhoneCommitView,
ChangeEmailInitiateView, ChangeEmailVerifyNewView, ChangeEmailCommitView,
CertificationSubmitView,EditorImageView,
CourseListView, CourseDetailView,
CourseCollectionView,CourseSubscriptionView,CourseProgressView,ExerciseSubmissionView,
GalleryListView,GalleryDetailView,GalleryCollectionView,
CommunityListView,CommunityPostDetailView,CommunityPostListCreateView,CommunityReplyCreateView,CommunityPostDestroyView,CommunityPostLikeView,
)


urlpatterns = [
    path('auth/register/', UserRegisterView.as_view(), name='auth_register'),
    path('auth/login/', UserLoginView.as_view(), name='auth_login'),
    path('my/profile/', UserProfileView.as_view(), name='my_profile'),
    path('auth/profile/avatar/', AvatarUpdateView.as_view(), name='auth_profile_avatar'),
    path('auth/forgot-password/send-code/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('auth/reset-password/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('auth/change-phone/initiate-verification/', ChangePhoneInitiateView.as_view(), name='change_phone_initiate'),
    path('auth/change-phone/verify-new/', ChangePhoneVerifyNewView.as_view(), name='change_phone_verify_new'),
    path('auth/change-phone/commit/', ChangePhoneCommitView.as_view(), name='change_phone_commit'),
    path('auth/change-mail/initiate-verification/', ChangeEmailInitiateView.as_view(), name='change_email_initiate'),
    path('auth/change-mail/verify-new/', ChangeEmailVerifyNewView.as_view(), name='change_email_verify_new'),
    path('auth/change-mail/commit/', ChangeEmailCommitView.as_view(), name='change_email_commit'),
    path('certification/submit/', CertificationSubmitView.as_view(), name='certification_submit'),
    path('uploads/editor-image/', EditorImageView.as_view(), name='editor-image-upload'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<int:pk>/subscribe/', CourseSubscriptionView.as_view(), name='course-subscribe'),
    path('courses/<int:pk>/collect/', CourseCollectionView.as_view(), name='course-collect'),
    path('courses/<int:pk>/progress/', CourseProgressView.as_view(), name='course-progress'),
    path('courses/<int:course_pk>/chapters/<int:chapter_pk>/submit/', ExerciseSubmissionView.as_view(), name='exercise-submit'),
    path('gallery/works/', GalleryListView.as_view(), name='gallery-list'),
    path('gallery/works/<int:pk>/', GalleryDetailView.as_view(), name='gallery-detail'),
    path('gallery/works/<int:pk>/collect/', GalleryCollectionView.as_view(), name='gallery-collect'),
    path('communities/', CommunityListView.as_view(), name='community-list'),
    path('communities/<int:community_pk>/posts/', 
         CommunityPostListCreateView.as_view(), name='community-post-list-create'),
    path('communities/<int:community_pk>/posts/<int:post_pk>/', 
         CommunityPostDetailView.as_view(), name='community-post-detail'),  
    path('posts/<int:pk>/', 
         CommunityPostDestroyView.as_view(), name='community-post-delete'), 
    path('posts/<int:pk>/like/', 
         CommunityPostLikeView.as_view(), name='community-post-like'),        
    path('posts/<int:pk>/replies/', 
         CommunityReplyCreateView.as_view(), name='post-reply-create'),
    ]
