# backend/api/urls.py
from django.urls import path
from .views import (UserRegisterView,UserSearchView,UserLoginView,UserProfileView,
ChangePhoneInitiateView, ChangePhoneVerifyNewView, ChangePhoneCommitView,
ChangeEmailInitiateView, ChangeEmailVerifyNewView, ChangeEmailCommitView,
CertificationSubmitView,EditorImageView,PasswordResetConfirmView,PasswordResetRequestView,
CourseListView, CourseDetailView,CourseCreateView,
CourseCollectionView,CourseSubscriptionView,CourseProgressView,ExerciseSubmissionView,
GalleryListView,GalleryDetailView,GalleryCollectionView,
GalleryItemCreateView,GalleryDownloadView,
CommunityCreateView,CommunityListView,CommunityPostDetailView,
CommunityPostListView,CommunityPostCreateView,CommunityReplyCreateView,
CommunityPostDestroyView,CommunityPostLikeView,CommunityDetailView,
MessageThreadListCreateView,MessageThreadRetrieveDestroyView,
MyCollectionsView,MySupportedView,MyCreationsView,MyParticipationsView,
CourseUpdateView,GalleryItemUpdateView,CommunityUpdateView)

def community_post_view(request, *args, **kwargs):
    if request.method == 'POST':
        return CommunityPostCreateView.as_view()(request, *args, **kwargs)
    return CommunityPostListView.as_view()(request, *args, **kwargs)

urlpatterns = [
    path('auth/register/', UserRegisterView.as_view(), name='auth_register'),
    path('auth/login/', UserLoginView.as_view(), name='auth_login'),
    path('auth/profile', UserProfileView.as_view(), name='auth_profile_update'),
    path('auth/forgot-password/send-code/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('auth/reset-password/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('auth/change-phone/initiate-verification/', ChangePhoneInitiateView.as_view(), name='change_phone_initiate'),
    path('auth/change-phone/verify-new/', ChangePhoneVerifyNewView.as_view(), name='change_phone_verify_new'),
    path('auth/change-phone/commit/', ChangePhoneCommitView.as_view(), name='change_phone_commit'),
    path('auth/change-mail/initiate-verification/', ChangeEmailInitiateView.as_view(), name='change_email_initiate'),
    path('auth/change-mail/verify-new/', ChangeEmailVerifyNewView.as_view(), name='change_email_verify_new'),
    path('auth/change-mail/commit/', ChangeEmailCommitView.as_view(), name='change_email_commit'),
    path('certification/submit/', CertificationSubmitView.as_view(), name='certification_submit'),
    path('uploads/editor-image/', EditorImageView.as_view(), name='editor-image-upload'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<int:pk>/subscribe/', CourseSubscriptionView.as_view(), name='course-subscribe'),
    path('courses/<int:pk>/collect/', CourseCollectionView.as_view(), name='course-collect'),
    path('courses/<int:pk>/progress/', CourseProgressView.as_view(), name='course-progress'),
    path('courses/<int:course_pk>/chapters/<int:chapter_pk>/submit/', ExerciseSubmissionView.as_view(), name='exercise-submit'),
    path('gallery/works/', GalleryListView.as_view(), name='gallery-list'),
    path('gallery/works/<int:pk>/', GalleryDetailView.as_view(), name='gallery-detail'),
    path('gallery/works/<int:pk>/download/', GalleryDownloadView.as_view(), name='gallery-download'),
    path('gallery/works/<int:pk>/collect/', GalleryCollectionView.as_view(), name='gallery-collect'),
    path('communities/', CommunityListView.as_view(), name='community-list'),
    path('communities/<int:pk>/', CommunityDetailView.as_view(), name='community-detail'),
    path('communities/<int:community_pk>/posts/', community_post_view, name='community-post-list-create'),
    path('communities/<int:community_pk>/posts/<int:post_pk>/', 
         CommunityPostDetailView.as_view(), name='community-post-detail'),  
    path('posts/<int:pk>/', 
         CommunityPostDestroyView.as_view(), name='community-post-delete'), 
    path('posts/<int:pk>/like/', 
         CommunityPostLikeView.as_view(), name='community-post-like'),        
    path('posts/<int:pk>/replies/', 
         CommunityReplyCreateView.as_view(), name='post-reply-create'),
    path('my/messages/', MessageThreadListCreateView.as_view(), name='my-messages-list-create'),
    path('my/messages/<int:pk>/', MessageThreadRetrieveDestroyView.as_view(), name='my-messages-detail-destroy'),
    path('users/search/', UserSearchView.as_view(), name='user-search'),
    path('my/collections/', MyCollectionsView.as_view(), name='my-collections'),
    path('my/supported/', MySupportedView.as_view(), name='my-supported'),
    path('my/creations/', MyCreationsView.as_view(), name='my-creations'),
    path('my/participations/', MyParticipationsView.as_view(), name='my-participations'),
    path('my/profile/', UserProfileView.as_view(), name='my_profile'),
    path('creator/courses/', CourseCreateView.as_view(), name='course-create'),
    path('creator/courses/<int:pk>/', CourseUpdateView.as_view(), name='course-update'),
    path('creator/gallery/', GalleryItemCreateView.as_view(), name='gallery-create'),
    path('creator/gallery/<int:pk>/', GalleryItemUpdateView.as_view(), name='gallery-update'),
    path('creator/communities/<int:pk>/', CommunityUpdateView.as_view(), name='community-update'),
    path('creator/communities/', CommunityCreateView.as_view(), name='community-create'),
    ]
